server:
  port: 9091

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth
    password: auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/