server:
  port: 9092

spring:
  cloud:
    openfeign:
      client:
        config:
          account:
            url: http://localhost:9090/api/v1/accounts
  application:
    name: calendar
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth
    password: auth
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

aws:
  s3:
    buckets:
      photo: photo-calendar
  region: eu-west-1