server:
  port: 0

spring:
  application:
    name: calendar
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth
    password: auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

aws:
  region: eu-west-1
  bucket-name: test