server:
  port: 0

spring:
  application:
    name: calendar
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth
    password: auth
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

aws:
  s3:
    buckets:
      photo: photo-calendar
  region: eu-west-1