server:
  port: 9090

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth
    password: auth
  jpa:
    hibernate:
      ddl-auto: update